spring.application.name=skill-8

# PostgreSQL connection (Neon)
spring.datasource.url=jdbc:postgresql://ep-orange-sky-ad0zh8n6-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_xh4GYXsTQdN8

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=ihfuwye8ry48757932809312749865874rwebfufsanddhiewiurriukdkw
jwt.expiration=3900000

# Server port
server.port=8086

